apiVersion: v1
kind: ConfigMap
metadata:
  name: rotten-chess-config
data:
  PLAYER_STATS_TABLE: rotten-chess-PlayerStatsTable
  PROCESSED_GAMES_TABLE: rotten-chess-ProcessedGamesTable
  SQS_QUEUE_URL: "https://sqs.{{ .Values.region }}.amazonaws.com/{{ .Values.account_id }}/rotten-chess-GameQueue"