AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Production Rotten Chess Functions

Parameters:
  VPC:
    Type: String
  SecurityGroup:
    Type: String
  PrivateSubnet:
    Type: String
  GameImportsTable:
    Type: String
  TrackedPlayersTable:
    Type: String
  PlayerStatsTable:
    Type: String
  ProcessedGamesTable:
    Type: String
  LeaderboardHistoryTable:
    Type: String
  GameQueue:
    Type: String

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaPermissions
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:*
                  - s3:*
                  - sqs:*
                  - ec2:*
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - secretsmanager:GetSecretValue
                Resource: "*"
  
  StepFunctionsExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StepFunctionPermissions
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 
                  - lambda:InvokeFunction
                  - logs:*
                Resource: "*"

  # Infrastructure-based Functions
  ImportPlayerGamesLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ImportPlayerGamesFunction}'
      RetentionInDays: 14

  EnqueueDynamoDBItemsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${EnqueueDynamoDBItemsFunction}'
      RetentionInDays: 14

  ImportPlayerGamesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../functions/import_player_games/
      Handler: import_player_games.lambda_handler
      Runtime: python3.12
      FunctionName: rotten-chess-ImportPlayerGames
      Timeout: 300
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          GAME_IMPORTS_TABLE: !Ref GameImportsTable
          TRACKED_PLAYERS_TABLE: !Ref TrackedPlayersTable
          PLAYER_STATS_TABLE: !Ref PlayerStatsTable
          SECRET_ARN: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:rotten-chess/user-agent-NKXP8b
      Architectures:
        - x86_64
  
  EnqueueDynamoDBItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../functions/enqueue_dynamodb_items/
      Handler: enqueue_dynamodb_items.lambda_handler
      Runtime: python3.12
      FunctionName: rotten-chess-EnqueueDynamoDBItems
      Timeout: 60 
      MemorySize: 128  
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          GAME_IMPORTS_TABLE: !Ref GameImportsTable
          SQS_QUEUE_URL: !Ref GameQueue
      Architectures:
        - x86_64
    
  PrivateLinkProvisionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../functions/provision_privatelinks/
      Handler: provision_privatelinks.lambda_handler
      Runtime: python3.12
      FunctionName: rotten-chess-PrivateLinkProvision
      Timeout: 60 
      MemorySize: 128  
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          VPC_ID: !Ref VPC
          SUBNET_ID: !Ref PrivateSubnet
          SECURITY_GROUP_ID: !Ref SecurityGroup
      Architectures:
        - x86_64

  PrivateLinkDeprovisionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../functions/deprovision_privatelinks/
      Handler: deprovision_privatelinks.lambda_handler
      Runtime: python3.12
      FunctionName: rotten-chess-PrivateLinkDeprovision
      Timeout: 60 
      MemorySize: 128  
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
  
  CheckQueueFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../functions/check_queue/
      Handler: check_queue.lambda_handler
      Runtime: python3.12
      FunctionName: rotten-chess-CheckQueue
      Timeout: 60 
      MemorySize: 128  
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          SQS_QUEUE_URL: !Ref GameQueue
      Architectures:
        - x86_64
  
  DeleteDynamoDBItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../functions/delete_dynamodb_items/
      Handler: delete_dynamodb_items.lambda_handler
      Runtime: python3.12
      FunctionName: rotten-chess-DeleteDynamoDBItems
      Timeout: 120 
      MemorySize: 128  
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          GAME_IMPORTS_TABLE: !Ref GameImportsTable
          PROCESSED_GAMES_TABLE: !Ref ProcessedGamesTable
      Architectures:
        - x86_64
  
  UpdateLeaderboardHistoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../functions/update_leaderboard_history/
      Handler: update_leaderboard_history.lambda_handler
      Runtime: python3.12
      FunctionName: rotten-chess-UpdateLeaderboardHistory
      Timeout: 60 
      MemorySize: 128  
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          PLAYER_STATS_TABLE: !Ref PlayerStatsTable
          LEADERBOARD_HISTORY_TABLE: !Ref LeaderboardHistoryTable
      Architectures:
        - x86_64
  
  # API Functions
  GetPlayerStatsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../functions/api/get_player_stats/
      Handler: get_player_stats.lambda_handler
      Runtime: python3.12
      FunctionName: rotten-chess-GetPlayerStats
      Timeout: 60 
      MemorySize: 128  
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          PLAYER_STATS_TABLE: !Ref PlayerStatsTable
      Architectures:
        - x86_64
  
  BatchGetPlayerStatsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../functions/api/batch_get_player_stats/
      Handler: batch_get_player_stats.lambda_handler
      Runtime: python3.12
      FunctionName: rotten-chess-BatchGetPlayerStats
      Timeout: 60 
      MemorySize: 128  
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          PLAYER_STATS_TABLE: !Ref PlayerStatsTable
      Architectures:
        - x86_64

  GetPlayersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../functions/api/get_players/
      Handler: get_players.lambda_handler
      Runtime: python3.12
      FunctionName: rotten-chess-GetPlayers
      Timeout: 60 
      MemorySize: 128  
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          PLAYER_STATS_TABLE: !Ref PlayerStatsTable
      Architectures:
        - x86_64
    
  GetLeaderboardHistoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../functions/api/get_leaderboard_history/
      Handler: get_leaderboard_history.lambda_handler
      Runtime: python3.12
      FunctionName: rotten-chess-GetLeaderboardHistory
      Timeout: 60 
      MemorySize: 128  
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          LEADERBOARD_HISTORY_TABLE: !Ref LeaderboardHistoryTable
      Architectures:
        - x86_64
  
  # Step Functions
  StateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: rotten-chess-StateMachine
      RoleArn: !GetAtt StepFunctionsExecutionRole.Arn
      DefinitionString: !Sub |
        {
          "Comment": "State machine to import, provision, enqueue, and deprovision.",
          "StartAt": "Parallel",
          "States": {
            "Parallel": {
              "Type": "Parallel",
              "Branches": [
                {
                  "StartAt": "Import Player Games",
                  "States": {
                    "Import Player Games": {
                      "Type": "Task",
                      "Resource": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:rotten-chess-ImportPlayerGames:$LATEST",
                      "Parameters": {
                        "FunctionName": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:rotten-chess-ImportPlayerGames:$LATEST"
                      },
                      "ResultPath": "$.importResult",
                      "Retry": [
                        {
                          "ErrorEquals": [
                            "Lambda.ServiceException",
                            "Lambda.AWSLambdaException",
                            "Lambda.SdkClientException",
                            "Lambda.TooManyRequestsException"
                          ],
                          "IntervalSeconds": 1,
                          "MaxAttempts": 3,
                          "BackoffRate": 2
                        }
                      ],
                      "End": true
                    }
                  }
                },
                {
                  "StartAt": "Provision PrivateLinks",
                  "States": {
                    "Provision PrivateLinks": {
                      "Type": "Task",
                      "Resource": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:rotten-chess-PrivateLinkProvision:$LATEST",
                      "Parameters": {
                        "FunctionName": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:rotten-chess-PrivateLinkProvision:$LATEST"
                      },
                      "ResultPath": "$.provisionResult",
                      "Retry": [
                        {
                          "ErrorEquals": [
                            "Lambda.ServiceException",
                            "Lambda.AWSLambdaException",
                            "Lambda.SdkClientException",
                            "Lambda.TooManyRequestsException"
                          ],
                          "IntervalSeconds": 1,
                          "MaxAttempts": 3,
                          "BackoffRate": 2
                        }
                      ],
                      "End": true
                    }
                  }
                }
              ],
              "Next": "Enqueue DynamoDB items"
            },
            "Enqueue DynamoDB items": {
              "Type": "Task",
              "Resource": "arn:aws:states:::lambda:invoke",
              "Parameters": {
                "FunctionName": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:rotten-chess-EnqueueDynamoDBItems:$LATEST",
                "Payload.$": "$"
              },
              "Retry": [
                {
                  "ErrorEquals": [
                    "Lambda.ServiceException",
                    "Lambda.AWSLambdaException",
                    "Lambda.SdkClientException",
                    "Lambda.TooManyRequestsException"
                  ],
                  "IntervalSeconds": 1,
                  "MaxAttempts": 3,
                  "BackoffRate": 2
                }
              ],
              "Next": "Check Queue"
            },
            "Check Queue": {
              "Type": "Task",
              "Resource": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:rotten-chess-CheckQueue:$LATEST",
              "Parameters": {
                "FunctionName": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:rotten-chess-CheckQueue:$LATEST"
              },
              "Next": "Is Queue Empty"
            },
            "Is Queue Empty": {
              "Type": "Choice",
              "Choices": [
                {
                  "Variable": "$.isEmpty",
                  "BooleanEquals": true,
                  "Next": "Deprovision PrivateLinks"
                }
              ],
              "Default": "Wait and Recheck Queue"
            },
            "Wait and Recheck Queue": {
              "Type": "Wait",
              "Seconds": 120,
              "Next": "Check Queue"
            },
            "Deprovision PrivateLinks": {
              "Type": "Task",
              "Resource": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:rotten-chess-PrivateLinkDeprovision:$LATEST",
              "Parameters": {
                "FunctionName": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:rotten-chess-PrivateLinkDeprovision:$LATEST"
              },
              "Retry": [
                {
                  "ErrorEquals": [
                    "Lambda.ServiceException",
                    "Lambda.AWSLambdaException",
                    "Lambda.SdkClientException",
                    "Lambda.TooManyRequestsException"
                  ],
                  "IntervalSeconds": 1,
                  "MaxAttempts": 3,
                  "BackoffRate": 2
                }
              ],
              "Next": "Delete DynamoDB Items"
            },
            "Delete DynamoDB Items": {
              "Type": "Task",
              "Resource": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:rotten-chess-DeleteDynamoDBItems:$LATEST",
              "Parameters": {
                "FunctionName": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:rotten-chess-DeleteDynamoDBItems:$LATEST"
              },
              "Retry": [
                {
                  "ErrorEquals": [
                    "Lambda.ServiceException",
                    "Lambda.AWSLambdaException",
                    "Lambda.SdkClientException",
                    "Lambda.TooManyRequestsException"
                  ],
                  "IntervalSeconds": 1,
                  "MaxAttempts": 3,
                  "BackoffRate": 2
                }
              ],
              "End": true
            }
          }
        }

Outputs:
  GetPlayerStatsFunction:
    Description: ARN of the GetPlayerStats Lambda function
    Value: !GetAtt GetPlayerStatsFunction.Arn
  
  BatchGetPlayerStatsFunction:
    Description: ARN of the BatchGetPlayerStats Lambda function
    Value: !GetAtt BatchGetPlayerStatsFunction.Arn

  GetPlayersFunction:
    Description: ARN of the GetPlayers Lambda function
    Value: !GetAtt GetPlayersFunction.Arn
  
  GetLeaderboardHistoryFunction:
    Description: ARN of the GetLeaderboardHistory Lambda function
    Value: !GetAtt GetLeaderboardHistoryFunction.Arn

  LambdaExecutionRole:
    Description: ARN of the Lambda Execution Role
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: rotten-chess-LambdaExecutionRole
  
  StepFunctionsExecutionRole:
    Description: ARN of the Step Functions Execution Role
    Value: !GetAtt StepFunctionsExecutionRole.Arn
    Export:
      Name: rotten-chess-StepFunctionsExecutionRole