AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Main production template Rotten Chess

Resources:
  InfrastructureStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./infrastructure.yaml

  FunctionsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./functions.yaml
      Parameters:
        VPC: !GetAtt InfrastructureStack.Outputs.VPC
        SecurityGroup: !GetAtt InfrastructureStack.Outputs.SecurityGroup
        PrivateSubnet: !GetAtt InfrastructureStack.Outputs.PrivateSubnet
        GameImportsTable: !GetAtt InfrastructureStack.Outputs.GameImportsTable
        TrackedPlayersTable: !GetAtt InfrastructureStack.Outputs.TrackedPlayersTable
        PlayerStatsTable: !GetAtt InfrastructureStack.Outputs.PlayerStatsTable
        LeaderboardHistoryTable: !GetAtt InfrastructureStack.Outputs.LeaderboardHistoryTable
        GameQueue: !GetAtt InfrastructureStack.Outputs.GameQueue

  APIStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./api.yaml
      Parameters:
        GetPlayerStatsFunction: !GetAtt FunctionsStack.Outputs.GetPlayerStatsFunction
        BatchGetPlayerStatsFunction: !GetAtt FunctionsStack.Outputs.BatchGetPlayerStatsFunction
        GetPlayersFunction: !GetAtt FunctionsStack.Outputs.GetPlayersFunction
        GetLeaderboardHistoryFunction: !GetAtt FunctionsStack.Outputs.GetLeaderboardHistoryFunction