name: Security tests

on:
  workflow_dispatch:

jobs: 
  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with: 
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install checkov
      - run: |
          checkov --directory .
