name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test-and-revert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest tests/
      continue-on-error: true
      id: pytest

    - name: Check test result
      if: steps.pytest.outcome == 'failure'
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git revert -m 1 HEAD
        git push origin main

    - name: Success message
      if: steps.pytest.outcome == 'success'
      run: echo "Tests passed successfully"
